- name: install nfs server
  apt:
    name: nfs-kernel-server

- name: partition shows disk
  parted:
    device: "/dev/disk/by-id/{{ external_disk_id }}"
    name: SHOWS
    number: 1
    label: gpt
    state: present

- name: format shows disk
  filesystem:
    fstype: ext4
    dev: "/dev/disk/by-partlabel/SHOWS"

- name: mount shows disk
  mount:
    path: "/shows"
    src: PARTLABEL=SHOWS
    fstype: ext4
    opts: "acl,user_xattr,nosuid,nofail"
    state: mounted

- name: create test directory
  file:
    path: "/shows/test"
    state: directory
    owner: root
    group: ubuntu
    mode: 0775

- name: add export entry
  lineinfile:
    path: /etc/exports
    regexp: '^/shows'
    line: "/shows   {{ export_client }}(mp,rw,async,no_subtree_check,root_squash)"

- name: export the filesystem
  shell: exportfs  {{ export_client }}:/shows
