global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
{% for node in nodes %}
      - targets: ['{{ node.private_ip }}:9100']
        labels:
          host: '{{ node.name }}'
{% endfor %}



