- name: install nfs client
  yum:
    name: nfs-utils
    state: present

- name: mount shows nfs
  mount:
    path: "/shows"
    src: "{{ nfs_server }}:/shows"
    fstype: nfs
    opts: "vers=4,rw,hard,nosuid,nofail"
    state: mounted


