- name: install golang
  yum:
    name: golang

- name: install make
  yum:
    name: make

- name: install git
  yum:
    name: git

- name: clone repository
  git:
    repo: https://github.com/parlaynu/fsutils.git
    dest: fsutils

- name: build tools
  shell: cd fsutils && make all

- name: install tools
  copy:
    remote_src: yes
    src: fsutils/bin/
    dest: bin

